server:
  port: 8089

management:
    port: 8090
    security:
        enabled: false

security.ignored: /**

exchangeServerMappings:
  app2devauto:
    endpoint:
      url: https://outlook.office365.com/EWS/Exchange.asmx
      autodiscover: false
    creds:
      exchangeUsername: impersonation@ttops.onmicrosoft.com
      exchangePassword: T1metradeDEV
      accessType: IMPERSONATION
  app2baycolonyfitness:
    endpoint:
      url: https://outlook.office365.com/EWS/Exchange.asmx
      autodiscover: false
    creds:
      exchangeUsername: impersonation@ttops.onmicrosoft.com
      exchangePassword: T1metradeDEV
      accessType: IMPERSONATION

configurationProvider:
  singleConfigUrl: http://plat01-ews-dev.am-use01.ttops.net:8093/api/{accountId}/ews
  allAccountsConfigUrl: http://plat01-ews-dev.am-use01.ttops.net:8093/api/list-with-accounts?configKey=ews

cacheSpecs:
  folders: maximumSize=10000
  configurations-meta: maximumSize=10000
  configurations-data: maximumSize=10000,expireAfterWrite=15m

timetrade:
  eapi.client:
    host: http://tesa-eapi:8080
    version: 7.2
  soap.credentials.path: classpath:credentials.json

resourcesSyncPeriod: 14400

redisDb:
  host: localhost #plat-shared-dev.xssbwt.0001.use1.cache.amazonaws.com
  port: 6379

#xx/yy - in "rate" means xx accounts then yy sec delay then xx subs again
subscriptions:
  ewsApiVersion: Exchange2010_SP1
  heartBeat: 300
  rate: 50/5
  reattempts:
    maxTimes: 3
    minutes: 5

recurringEventsPreloadPeriod: 12
initialAvailabilityLoadPeriod: 12

logIncomingXml: true

kafka:
  bootstrapServers: localhost:9092
  topicPattern: "{accountId}-notifications"
  numberOfConsumers: 1
