//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.07 at 08:14:05 PM EET 
//


package com.ms.ews;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BaseRequestType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BaseRequestType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BaseRequestType", namespace = "http://schemas.microsoft.com/exchange/services/2006/messages")
@XmlSeeAlso({
    GetInboxRulesRequestType.class,
    SubscribeType.class,
    ExportItemsType.class,
    DeleteFolderType.class,
    GetUserConfigurationType.class,
    GetPhoneCallInformationType.class,
    CreateUserConfigurationType.class,
    CreateItemType.class,
    RefreshSharingFolderType.class,
    GetAttachmentType.class,
    GetUserAvailabilityRequestType.class,
    FindFolderType.class,
    FindMailboxStatisticsByKeywordsType.class,
    GetMailTipsType.class,
    DeleteUserConfigurationType.class,
    GetPasswordExpirationDateType.class,
    DeleteAttachmentType.class,
    GetServiceConfigurationType.class,
    ResolveNamesType.class,
    GetSharingMetadataType.class,
    GetSharingFolderType.class,
    GetRoomListsType.class,
    GetStreamingEventsType.class,
    CreateFolderType.class,
    GetEventsType.class,
    DeleteItemType.class,
    ExpandDLType.class,
    EmptyFolderType.class,
    GetRoomsType.class,
    UpdateInboxRulesRequestType.class,
    CreateManagedFolderRequestType.class,
    ConvertIdType.class,
    UnsubscribeType.class,
    GetFolderType.class,
    UploadItemsType.class,
    UpdateItemType.class,
    GetUserOofSettingsRequest.class,
    FindConversationType.class,
    GetMessageTrackingReportRequestType.class,
    ApplyConversationActionType.class,
    SyncFolderHierarchyType.class,
    GetItemType.class,
    CreateAttachmentType.class,
    FindItemType.class,
    GetServerTimeZonesType.class,
    UpdateUserConfigurationType.class,
    SetUserOofSettingsRequest.class,
    SendItemType.class,
    FindMessageTrackingReportRequestType.class,
    PlayOnPhoneType.class,
    SyncFolderItemsType.class,
    UpdateFolderType.class,
    DisconnectPhoneCallType.class,
    BaseDelegateType.class,
    BaseMoveCopyFolderType.class,
    BaseMoveCopyItemType.class
})
public abstract class BaseRequestType {


}
