//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.07 at 08:14:05 PM EET 
//


package com.ms.ews;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BaseResponseMessageType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BaseResponseMessageType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ResponseMessages" type="{http://schemas.microsoft.com/exchange/services/2006/messages}ArrayOfResponseMessagesType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BaseResponseMessageType", namespace = "http://schemas.microsoft.com/exchange/services/2006/messages", propOrder = {
    "responseMessages"
})
@XmlSeeAlso({
    CreateUserConfigurationResponseType.class,
    UnsubscribeResponseType.class,
    UpdateFolderResponseType.class,
    ExportItemsResponseType.class,
    ApplyConversationActionResponseType.class,
    CreateItemResponseType.class,
    FindMailboxStatisticsByKeywordsResponseType.class,
    DeleteAttachmentResponseType.class,
    GetServerTimeZonesResponseType.class,
    SubscribeResponseType.class,
    UpdateUserConfigurationResponseType.class,
    SendNotificationResponseType.class,
    MoveFolderResponseType.class,
    SyncFolderHierarchyResponseType.class,
    UploadItemsResponseType.class,
    GetUserConfigurationResponseType.class,
    DeleteFolderResponseType.class,
    GetEventsResponseType.class,
    ResolveNamesResponseType.class,
    SendItemResponseType.class,
    GetFolderResponseType.class,
    GetItemResponseType.class,
    GetStreamingEventsResponseType.class,
    SyncFolderItemsResponseType.class,
    ConvertIdResponseType.class,
    CopyItemResponseType.class,
    CreateFolderResponseType.class,
    CreateManagedFolderResponseType.class,
    EmptyFolderResponseType.class,
    FindFolderResponseType.class,
    FindItemResponseType.class,
    CreateAttachmentResponseType.class,
    ExpandDLResponseType.class,
    CopyFolderResponseType.class,
    DeleteItemResponseType.class,
    GetAttachmentResponseType.class,
    MoveItemResponseType.class,
    DeleteUserConfigurationResponseType.class,
    UpdateItemResponseType.class
})
public class BaseResponseMessageType {

    @XmlElement(name = "ResponseMessages", required = true)
    protected ArrayOfResponseMessagesType responseMessages;

    /**
     * Gets the value of the responseMessages property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfResponseMessagesType }
     *     
     */
    public ArrayOfResponseMessagesType getResponseMessages() {
        return responseMessages;
    }

    /**
     * Sets the value of the responseMessages property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfResponseMessagesType }
     *     
     */
    public void setResponseMessages(ArrayOfResponseMessagesType value) {
        this.responseMessages = value;
    }

}
