//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.07 at 08:14:05 PM EET 
//


package com.ms.ews;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CalendarFolderType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CalendarFolderType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://schemas.microsoft.com/exchange/services/2006/types}BaseFolderType">
 *       &lt;sequence>
 *         &lt;element name="SharingEffectiveRights" type="{http://schemas.microsoft.com/exchange/services/2006/types}CalendarPermissionReadAccessType" minOccurs="0"/>
 *         &lt;element name="PermissionSet" type="{http://schemas.microsoft.com/exchange/services/2006/types}CalendarPermissionSetType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CalendarFolderType", propOrder = {
    "sharingEffectiveRights",
    "permissionSet"
})
public class CalendarFolderType
    extends BaseFolderType
{

    @XmlElement(name = "SharingEffectiveRights")
    @XmlSchemaType(name = "string")
    protected CalendarPermissionReadAccessType sharingEffectiveRights;
    @XmlElement(name = "PermissionSet")
    protected CalendarPermissionSetType permissionSet;

    /**
     * Gets the value of the sharingEffectiveRights property.
     * 
     * @return
     *     possible object is
     *     {@link CalendarPermissionReadAccessType }
     *     
     */
    public CalendarPermissionReadAccessType getSharingEffectiveRights() {
        return sharingEffectiveRights;
    }

    /**
     * Sets the value of the sharingEffectiveRights property.
     * 
     * @param value
     *     allowed object is
     *     {@link CalendarPermissionReadAccessType }
     *     
     */
    public void setSharingEffectiveRights(CalendarPermissionReadAccessType value) {
        this.sharingEffectiveRights = value;
    }

    /**
     * Gets the value of the permissionSet property.
     * 
     * @return
     *     possible object is
     *     {@link CalendarPermissionSetType }
     *     
     */
    public CalendarPermissionSetType getPermissionSet() {
        return permissionSet;
    }

    /**
     * Sets the value of the permissionSet property.
     * 
     * @param value
     *     allowed object is
     *     {@link CalendarPermissionSetType }
     *     
     */
    public void setPermissionSet(CalendarPermissionSetType value) {
        this.permissionSet = value;
    }

}
