//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.07 at 08:14:05 PM EET 
//


package com.ms.ews;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ConflictResolutionType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ConflictResolutionType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="NeverOverwrite"/>
 *     &lt;enumeration value="AutoResolve"/>
 *     &lt;enumeration value="AlwaysOverwrite"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ConflictResolutionType")
@XmlEnum
public enum ConflictResolutionType {

    @XmlEnumValue("NeverOverwrite")
    NEVER_OVERWRITE("NeverOverwrite"),
    @XmlEnumValue("AutoResolve")
    AUTO_RESOLVE("AutoResolve"),
    @XmlEnumValue("AlwaysOverwrite")
    ALWAYS_OVERWRITE("AlwaysOverwrite");
    private final String value;

    ConflictResolutionType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ConflictResolutionType fromValue(String v) {
        for (ConflictResolutionType c: ConflictResolutionType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
