//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.07 at 08:14:05 PM EET 
//


package com.ms.ews;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * Converts the passed source ids into the destination format. Change keys are not returned.
 * 
 * 
 * <p>Java class for ConvertIdType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ConvertIdType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://schemas.microsoft.com/exchange/services/2006/messages}BaseRequestType">
 *       &lt;sequence>
 *         &lt;element name="SourceIds" type="{http://schemas.microsoft.com/exchange/services/2006/types}NonEmptyArrayOfAlternateIdsType"/>
 *       &lt;/sequence>
 *       &lt;attribute name="DestinationFormat" use="required" type="{http://schemas.microsoft.com/exchange/services/2006/types}IdFormatType" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ConvertIdType", namespace = "http://schemas.microsoft.com/exchange/services/2006/messages", propOrder = {
    "sourceIds"
})
public class ConvertIdType
    extends BaseRequestType
{

    @XmlElement(name = "SourceIds", required = true)
    protected NonEmptyArrayOfAlternateIdsType sourceIds;
    @XmlAttribute(name = "DestinationFormat", required = true)
    protected IdFormatType destinationFormat;

    /**
     * Gets the value of the sourceIds property.
     * 
     * @return
     *     possible object is
     *     {@link NonEmptyArrayOfAlternateIdsType }
     *     
     */
    public NonEmptyArrayOfAlternateIdsType getSourceIds() {
        return sourceIds;
    }

    /**
     * Sets the value of the sourceIds property.
     * 
     * @param value
     *     allowed object is
     *     {@link NonEmptyArrayOfAlternateIdsType }
     *     
     */
    public void setSourceIds(NonEmptyArrayOfAlternateIdsType value) {
        this.sourceIds = value;
    }

    /**
     * Gets the value of the destinationFormat property.
     * 
     * @return
     *     possible object is
     *     {@link IdFormatType }
     *     
     */
    public IdFormatType getDestinationFormat() {
        return destinationFormat;
    }

    /**
     * Sets the value of the destinationFormat property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdFormatType }
     *     
     */
    public void setDestinationFormat(IdFormatType value) {
        this.destinationFormat = value;
    }

}
