//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.07 at 08:14:05 PM EET 
//


package com.ms.ews;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ConversationActionTypeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ConversationActionTypeType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="AlwaysCategorize"/>
 *     &lt;enumeration value="AlwaysDelete"/>
 *     &lt;enumeration value="AlwaysMove"/>
 *     &lt;enumeration value="Delete"/>
 *     &lt;enumeration value="Move"/>
 *     &lt;enumeration value="Copy"/>
 *     &lt;enumeration value="SetReadState"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ConversationActionTypeType")
@XmlEnum
public enum ConversationActionTypeType {

    @XmlEnumValue("AlwaysCategorize")
    ALWAYS_CATEGORIZE("AlwaysCategorize"),
    @XmlEnumValue("AlwaysDelete")
    ALWAYS_DELETE("AlwaysDelete"),
    @XmlEnumValue("AlwaysMove")
    ALWAYS_MOVE("AlwaysMove"),
    @XmlEnumValue("Delete")
    DELETE("Delete"),
    @XmlEnumValue("Move")
    MOVE("Move"),
    @XmlEnumValue("Copy")
    COPY("Copy"),
    @XmlEnumValue("SetReadState")
    SET_READ_STATE("SetReadState");
    private final String value;

    ConversationActionTypeType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ConversationActionTypeType fromValue(String v) {
        for (ConversationActionTypeType c: ConversationActionTypeType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
