//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.07 at 08:14:05 PM EET 
//


package com.ms.ews;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DelegateUserResponseMessageType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DelegateUserResponseMessageType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://schemas.microsoft.com/exchange/services/2006/messages}ResponseMessageType">
 *       &lt;sequence>
 *         &lt;element name="DelegateUser" type="{http://schemas.microsoft.com/exchange/services/2006/types}DelegateUserType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DelegateUserResponseMessageType", namespace = "http://schemas.microsoft.com/exchange/services/2006/messages", propOrder = {
    "delegateUser"
})
public class DelegateUserResponseMessageType
    extends ResponseMessageType
{

    @XmlElement(name = "DelegateUser")
    protected DelegateUserType delegateUser;

    /**
     * Gets the value of the delegateUser property.
     * 
     * @return
     *     possible object is
     *     {@link DelegateUserType }
     *     
     */
    public DelegateUserType getDelegateUser() {
        return delegateUser;
    }

    /**
     * Sets the value of the delegateUser property.
     * 
     * @param value
     *     allowed object is
     *     {@link DelegateUserType }
     *     
     */
    public void setDelegateUser(DelegateUserType value) {
        this.delegateUser = value;
    }

}
