//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.07 at 08:14:05 PM EET 
//


package com.ms.ews;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * Response message type for the FindMailboxStatisticsByKeywords web method.
 * 
 * 
 * <p>Java class for FindMailboxStatisticsByKeywordsResponseMessageType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FindMailboxStatisticsByKeywordsResponseMessageType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://schemas.microsoft.com/exchange/services/2006/messages}ResponseMessageType">
 *       &lt;sequence>
 *         &lt;element name="MailboxStatisticsSearchResult" type="{http://schemas.microsoft.com/exchange/services/2006/types}MailboxStatisticsSearchResultType"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FindMailboxStatisticsByKeywordsResponseMessageType", namespace = "http://schemas.microsoft.com/exchange/services/2006/messages", propOrder = {
    "mailboxStatisticsSearchResult"
})
public class FindMailboxStatisticsByKeywordsResponseMessageType
    extends ResponseMessageType
{

    @XmlElement(name = "MailboxStatisticsSearchResult", required = true)
    protected MailboxStatisticsSearchResultType mailboxStatisticsSearchResult;

    /**
     * Gets the value of the mailboxStatisticsSearchResult property.
     * 
     * @return
     *     possible object is
     *     {@link MailboxStatisticsSearchResultType }
     *     
     */
    public MailboxStatisticsSearchResultType getMailboxStatisticsSearchResult() {
        return mailboxStatisticsSearchResult;
    }

    /**
     * Sets the value of the mailboxStatisticsSearchResult property.
     * 
     * @param value
     *     allowed object is
     *     {@link MailboxStatisticsSearchResultType }
     *     
     */
    public void setMailboxStatisticsSearchResult(MailboxStatisticsSearchResultType value) {
        this.mailboxStatisticsSearchResult = value;
    }

}
