//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.07 at 08:14:05 PM EET 
//


package com.ms.ews;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ResolveNamesSearchScopeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ResolveNamesSearchScopeType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="ActiveDirectory"/>
 *     &lt;enumeration value="ActiveDirectoryContacts"/>
 *     &lt;enumeration value="Contacts"/>
 *     &lt;enumeration value="ContactsActiveDirectory"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ResolveNamesSearchScopeType")
@XmlEnum
public enum ResolveNamesSearchScopeType {

    @XmlEnumValue("ActiveDirectory")
    ACTIVE_DIRECTORY("ActiveDirectory"),
    @XmlEnumValue("ActiveDirectoryContacts")
    ACTIVE_DIRECTORY_CONTACTS("ActiveDirectoryContacts"),
    @XmlEnumValue("Contacts")
    CONTACTS("Contacts"),
    @XmlEnumValue("ContactsActiveDirectory")
    CONTACTS_ACTIVE_DIRECTORY("ContactsActiveDirectory");
    private final String value;

    ResolveNamesSearchScopeType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ResolveNamesSearchScopeType fromValue(String v) {
        for (ResolveNamesSearchScopeType c: ResolveNamesSearchScopeType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
