//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.07 at 08:14:05 PM EET 
//


package com.ms.ews;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SyncFolderItemsScopeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="SyncFolderItemsScopeType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="NormalItems"/>
 *     &lt;enumeration value="NormalAndAssociatedItems"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "SyncFolderItemsScopeType")
@XmlEnum
public enum SyncFolderItemsScopeType {

    @XmlEnumValue("NormalItems")
    NORMAL_ITEMS("NormalItems"),
    @XmlEnumValue("NormalAndAssociatedItems")
    NORMAL_AND_ASSOCIATED_ITEMS("NormalAndAssociatedItems");
    private final String value;

    SyncFolderItemsScopeType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static SyncFolderItemsScopeType fromValue(String v) {
        for (SyncFolderItemsScopeType c: SyncFolderItemsScopeType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
