//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.07 at 08:14:05 PM EET 
//


package com.ms.ews;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for UpdateInboxRulesResponseType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="UpdateInboxRulesResponseType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://schemas.microsoft.com/exchange/services/2006/messages}ResponseMessageType">
 *       &lt;sequence>
 *         &lt;element name="RuleOperationErrors" type="{http://schemas.microsoft.com/exchange/services/2006/types}ArrayOfRuleOperationErrorsType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UpdateInboxRulesResponseType", namespace = "http://schemas.microsoft.com/exchange/services/2006/messages", propOrder = {
    "ruleOperationErrors"
})
public class UpdateInboxRulesResponseType
    extends ResponseMessageType
{

    @XmlElement(name = "RuleOperationErrors")
    protected ArrayOfRuleOperationErrorsType ruleOperationErrors;

    /**
     * Gets the value of the ruleOperationErrors property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfRuleOperationErrorsType }
     *     
     */
    public ArrayOfRuleOperationErrorsType getRuleOperationErrors() {
        return ruleOperationErrors;
    }

    /**
     * Sets the value of the ruleOperationErrors property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfRuleOperationErrorsType }
     *     
     */
    public void setRuleOperationErrors(ArrayOfRuleOperationErrorsType value) {
        this.ruleOperationErrors = value;
    }

}
